parentPomVersion: 0.0.2-SNAPSHOT
sdkVersion: 1.11.15
modules:
 -
  name: cloudwatch
  classPrefix: AmazonCloudWatch
 -
  name: dynamodb
  package: dynamodbv2
  classPrefix: AmazonDynamoDB
 -
  name: ec2
  classPrefix: AmazonEC2
 -
  name: ecs
  classPrefix: AmazonECS
  serviceName: EC2 Container Service
 -
  name: iam
  package: identitymanagement
  classPrefix: AmazonIdentityManagement
 -
  name: kinesis
  classPrefix: AmazonKinesis
 -
  name: lambda
  classPrefix: AWSLambda
 -
  name: logs
  classPrefix: AWSLogs
  serviceName: CloudWatch Logs
 -
  name: machinelearning
  classPrefix: AmazonMachineLearning
  serviceName: Amazon Machine Learning
 -
  name: route53
  classPrefix: AmazonRoute53
  serviceName: Route53
 -
  name: ses
  package: simpleemail
  classPrefix: AmazonSimpleEmailService
  serviceName: Simple Email Service
 -
  name: simpledb
  classPrefix: AmazonSimpleDB
  serviceName: SimpleDB
  shutdownSupported: false
 -
  name: sns
  classPrefix: AmazonSNS
  serviceName: Simple Notification Service
 -
  name: sqs
  classPrefix: AmazonSQS
  serviceName: Simple Queue Service
 -
  name: sts
  package: securitytoken
  classPrefix: AWSSecurityTokenService
  serviceName: Security Token Service
